// src/engine/ai/planRanker.js
// Takes multiple candidate plans from the language model and ranks them 
// against the user's focus memory to pick the most realistic plan.

import { estimateTaskDuration } from './plannerMemory.js';

/**
 * 
 * @param {Array} candidatePlans - List of plan objects generated by the AI
 * @param {Object} parsedTask - Result from taskParser.js
 */
export function rankAndSelectBestPlan(candidatePlans, parsedTask) {
    if (!candidatePlans || candidatePlans.length === 0) return null;

    // Get historical context for this text
    const memoryDrivenDuration = estimateTaskDuration(parsedTask.raw);

    let bestScore = -9999;
    let bestPlan = candidatePlans[0];

    candidatePlans.forEach(plan => {
        let score = 0;

        // Deviancy Penalty: Don't let a generic 25m default override a professional long block
        // Weight the penalty less if we are in "Heavy Load" territory
        const weight = parsedTask.isHeavyCognitiveLoad ? 0.2 : 0.6;
        const diff = Math.abs(plan.duration - memoryDrivenDuration);
        score -= (diff * weight);

        // Reward for Professional Deep Work in high-volume scenarios
        if (parsedTask.isHeavyCognitiveLoad) {
            // Reward 90m+ blocks for heavy tasks
            if (plan.duration >= 90) score += 40;
            else if (plan.duration >= 45) score += 20;
            else score -= 30; // Penalize "toy" answers for professional loads
        } else {
            // Light tasks favoring Standard/Sprint
            if (plan.duration > 45) score -= 20;
            else score += 10;
        }

        // Urgency Bonus for Mega Blocks
        if (parsedTask.complexityScore >= 9 && plan.duration >= 60) {
            score += 15;
        }

        // Assign ranking
        plan._rankScore = score;

        if (score > bestScore) {
            bestScore = score;
            bestPlan = plan;
        }
    });

    // Attach a justification label based on ranking
    if (bestScore > 0) {
        bestPlan.rankJustification = `Adjusted to ${bestPlan.duration}m due to high cognitive load (${parsedTask.complexityScore}/10).`;
    } else {
        bestPlan.rankJustification = `Selected based on your memory profile for similar tasks.`;
    }

    return bestPlan;
}
